openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of "Contacts App"
servers:
  - url: http://127.0.0.1:3000
tags:
  - name: Contacts
    description: Operations with contacts.
  - name: Auth
    description: Auth operations.
paths:
  /api/contacts:
    get:
      $ref: '../swagger/path/contacts/get.yaml'
    post:
      $ref: '../swagger/path/contacts/post.yaml'
  /api/contacts/{id}:
    get:
      $ref: '../swagger/path/contacts/{id)/get.yaml'
    patch:
      $ref: '../swagger/path/contacts/{id)/patch.yaml'
    delete:
      $ref: '../swagger/path/contacts/{id)/delete.yaml'
  /api/auth/register:
    post:
      $ref: '../swagger/path/auth/register.yaml'
  /api/auth/login:
    post:
      $ref: '../swagger/path/auth/login.yaml'
  /api/auth/refresh:
    post:
      $ref: '../swagger/path/auth/refresh.yaml'
  /api/auth/send-reset-email:
    post:
      $ref: '../swagger/path/auth/send-reset-email.yaml'
  /api/auth/reset-password:
    post:
      $ref: '../swagger/path/auth/reset-password.yaml'
  /api/auth/logout:
    post:
      $ref: '../swagger/path/auth/logout.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
